# Travis-CI configuration file for VGMTrans
sudo: required
dist: trusty
language: generic

matrix:
  include:
    # GCC5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - libglib2.0-dev
            - libfluidsynth-dev
      env: CC='gcc-5' CXX='g++-5'
      before_install:
        - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
        - sudo apt-get update -qq
        - sudo apt-get install qtbase5-dev
    # LLVM4
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libglib2.0-dev
            - libfluidsynth-dev
      env: CC='clang-4.0' CXX='clang++-4.0'
      before_install:
        - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
        - sudo apt-get update -qq
        - sudo apt-get install qtbase5-dev
    # xcode7.3
    - os: osx
      before_install:
        - brew upgrade qt || brew install qt
        - brew upgrade fluid-synth || brew install fluid-synth

install:
  # We need CMake >= 3.5.0
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake-bin && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake-bin
      export PATH=${TRAVIS_BUILD_DIR}/cmake-bin/bin:${PATH}
    else
      # For good measure, since Travis includes 3.6.2 anyway
      brew upgrade cmake || brew install cmake
    fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j$(nproc || sysctl -n hw.ncpu)

branches:
  only:
    - master
